### PR TITLE
iszero and == for spoly in quotient ring

### LINKED ISSUE #691: Reduce elements of QuotientRing modulo ideal
**Describe the bug**
Elements of a QuotientRing are not reduced modulo the ideal defining the quotient.

**To Reproduce**
```
using Singular
R, (x,y) = polynomial_ring(QQ, ["x", "y"]);
Q, (a,b) = QuotientRing(R, Ideal(R, x-y));
a-b  # Returns x-y. Expected zero.
```

**Expected behavior**
Expected result: 0

**Information about your setup:**
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 13th Gen Intel(R) Core(TM) i5-1345U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, goldmont)

julia> using Pkg; Pkg.status(mode=PKGMODE_MANIFEST)
      Status `/tmp/singbug/Manifest.toml`
  [c3fe647b] AbstractAlgebra v0.31.0
  [f01c122e] BinaryWrappers v0.1.2
  [1f15a43c] CxxWrap v0.13.4
  [d5909c97] GroupsCore v0.4.0
  [692b3bcd] JLLWrappers v1.4.1
  [1914dd2f] MacroTools v0.5.10
  [2edaba10] Nemo v0.35.3
  [fa939f87] Pidfile v1.3.0
  [21216c6a] Preferences v1.4.0
  [fb686558] RandomExtensions v0.4.3
  [6c6a2e73] Scratch v1.2.0
  [bcd08a7b] Singular v0.18.9
  [e21ec000] Antic_jll v0.201.500+0
  [d9960996] Arb_jll v200.2300.0+0
  [fcfa6d1b] Calcium_jll v0.401.100+0
  [e134572f] FLINT_jll v200.900.7+0
  [e8aa6df9] GLPK_jll v5.0.1+0
  [656ef2d0] OpenBLAS32_jll v0.3.17+0
  [43d676ae] Singular_jll v403.203.202+0
  [f07e07eb] cddlib_jll v0.94.13+0
  [1493ae25] lib4ti2_jll v1.6.10+0
  [3eaa8342] libcxxwrap_julia_jll v0.9.7+3
  [ae4fbd8f] libsingular_julia_jll v0.36.0+0
  [0dad84c5] ArgTools
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [f43a241f] Downloads
  [7b1f6079] FileWatching
  [b77e0a4c] InteractiveUtils
  [b27032c2] LibCURL
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [ca575930] NetworkOptions
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [fa267f1f] TOML
  [a4e569a6] Tar
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll
  [781609d7] GMP_jll
  [deac9b47] LibCURL_jll
  [29816b5a] LibSSH2_jll
  [3a97d323] MPFR_jll
  [c8ffd9c3] MbedTLS_jll
  [14a3606d] MozillaCACerts_jll
  [4536629a] OpenBLAS_jll
  [83775a58] Zlib_jll
  [8e850b90] libblastrampoline_jll
  [8e850ede] nghttp2_jll
  [3f19e933] p7zip_jll

**Additional context**
In case QuotientRing works as intended, then I suggest explaining this in the documentation here:
[https://oscar-system.github.io/Singular.jl/dev/qring/](https://oscar-system.github.io/Singular.jl/dev/qring/)

### PR DESCRIPTION
**Pull request by hannes14**
resolves #691

### CODE REVIEW

File: src/poly/poly.jl [hunk 1]
```diff
@@ -711,7 +718,7 @@ end
 
 function (x::SPolyUnion{T} == y::SPolyUnion{T}) where T <: Nemo.RingElem
    check_parent(x, y)
-   GC.@preserve x y return Bool(libSingular.p_EqualPolys(x.ptr, y.ptr, parent(x).ptr))
+   return(iszero(x-y))
```
Comment (fingolfin) [inline src/poly/poly.jl:721]:
```suggestion
   return iszero(x-y)
```

File: src/poly/poly.jl [hunk 2]
```diff
@@ -711,7 +718,7 @@ end
...
 end
 
 function Base.isless(x::SPolyUnion{T}, y::SPolyUnion{T}) where T <: Nemo.RingElem
```
Comment (fingolfin) [inline src/poly/poly.jl:724]: Do we also need something similar here?

File: test/poly/poly-test.jl [hunk 3]
```diff
@@ -234,6 +234,13 @@ end
    @test trailing_coefficient(R()) == 0
 end
 
+@testset "poly.QuotientRing" begin
+    R, (x,y) = polynomial_ring(QQ, ["x", "y"])
+    Q, (a,b) = QuotientRing(R, Ideal(R, x-y))
+    @test iszero(a-b)
+    @test (a-b)==Q(0)
```
Comment (fingolfin) [inline test/poly/poly-test.jl:241]:
```suggestion
    @test (a-b) == Q(0)
    @test a == b
```

File: src/poly/poly.jl [hunk 4]
```diff
@@ -140,7 +140,14 @@ function one(R::PolyRingUnion)
...
+   if libSingular.is_qring(R.ptr)
+     GC.@preserve p x = libSingular.qring_simplify(p.ptr,R.ptr)
+     xx = R(x)
+     return xx.ptr.cpp_object == C_NULL
+   else
+     return p.ptr.cpp_object == C_NULL
+   end
 end
 
 function isone(p::SPolyUnion)
```
Comment (fingolfin) [inline src/poly/poly.jl:153]: doesn't `isone` also need a similar change?

File: src/poly/poly.jl (hunk 2 above)
Comment (hannes14) [reply src/poly/poly.jl:724]: I don't think so: the classes of 0 and 1 are special (and therefore also the operator ==), but otherwise
we work with any representat of the class (in the quotinet ring case)

File: src/poly/poly.jl (hunk 4 above)
Comment (hannes14) [reply src/poly/poly.jl:153]: Yes, coming soon

**Review by fingolfin — APPROVED** [review]
